### PR TITLE
Testing integration with zeebe-process-test

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This is not an actual proposal, but just playing around to see if it would be possible to integrate this module with `zeebe-process-test`, and any obstacles.

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/camunda-cloud/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/camunda-cloud/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing
- [ ] Ensure all PR checks are green

### CODE REVIEW

**Comment by npepinpe** [comment]
lol

OK :ok_hand:

**Comment by andrejpetras** [comment]
@npepinpe I like this.
I implemented this using the "hazelcast" exporter for the Quarkus extension.
But this is much better. I would like to switch to your solution in the Quarkus extension.

https://github.com/quarkiverse/quarkus-zeebe#testing

https://github.com/quarkiverse/quarkus-zeebe/tree/main/test/src/main/java/io/quarkiverse/zeebe/test

**Comment by andrejpetras** [comment]
@npepinpe ;) thanks for info

**Comment by npepinpe** [comment]
I think https://github.com/camunda-community-hub/zeebe-test-container/pull/289 will solve the issue, then it's just a matter of adding the integration with `zeebe-process-test`.

**Comment by npepinpe** [comment]
Superseded by #316

**Pull request closed without merging**
