### PR TITLE
Allow control of the container clock

### LINKED ISSUE #74: I can change the time of the broker
**Is your feature request related to a problem? Please describe.**
Sometimes, workflows have parts that are depending on the time or that time has passed. For example, a timer boundary event in a workflow. In order to test these parts, I need a way to manipulate the time.

**Describe the solution you'd like**
I can manipulate the time that is used by the broker from the outside.

**Describe alternatives you've considered**
Maybe, it is also possible to manipulate the time of the whole docker container.

**Additional context**

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Allows broker containers to use a controllable clock via an opt-in method `ZeebeBrokerNode#withContainerClockEnabled()`. When so configured, the user can then use `ZeebeBrokerNode#getClock()` and modify the time as described in `ContainerClock`.

`ContainerClock` supports the following operations:

- adding a relative time offset (negative or positive); time will keep ticking after this. Adding multiple offset is cumulative and does not reset the previous offset
- freezing the time to a fixed instant
- unfreezing time; time will start ticking relatively to the previously frozen instant
- resetting; time will be reset to the real system time

See the examples in `src/test/java/io/zeebe/containers/examples/clock` for more.

The default implementation of `ContainerClock` is `LibFakeTimeClock`, based on [libfaketime](https://github.com/wolfcw/libfaketime). This relies on a pre-compiled shared library which was compiled specifically for the default Zeebe container image, and may not work for custom images.

## Related issues

closes #74

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing
- [x] Ensure all PR checks are green

### CODE REVIEW

**Comment by npepinpe** [comment]
Some caveats here:

- The solution relies on a pre-compiled binary, which is not (AFAIK) portable. It probably won't work on different images.
- The pre-compiled binary is part of the repository. It's not that big, but it might be better to make it into a separate module, so the whole clock stuff is really opt-in. I don't know.
- Plenty of tests missing, but I opened the PR just to have an idea and get some feedback on the API.

**Comment by npepinpe** [comment]
@saig0 - no need to review this completely, but maybe just the `ContainerClock` interface to make sure it will work for you :slightly_smiling_face: You can see the `TimeTravelExampleTest` to get an idea of how it will look like in practice.

**Comment by npepinpe** [comment]
I now realize libfaketime is GPL licensed, which means if we were to distributed it with `zeebe-test-container` then it would also have to be GPL licensed. Then again I'm not a legal expert, so I'm unsure how that works for something like a Maven module. I think making it its own module (which is GPL licensed) and simply marking it as a dependency might be enough to work around this?

**Comment by oleschoenburg** [comment]
`libfaketime` is also available as a debian package so maybe we could just [build a custom image](https://www.testcontainers.org/features/creating_images/#dockerfile-dsl) based on the official zeebe image that has `libfaketime` installed:

```
new GenericContainer(
        new ImageFromDockerfile()
                .withDockerfileFromBuilder(builder ->
                        builder
                                .from("camunda/zeebe:1.2.2")
                                .run("apt update")
                                .run("apt install -y libfaketime")
                                .build()));
```

I think it should then be possible to reuse this image so that we don't have to pay the cost for downloading or installing `libfaketime` over and over again.

**Comment by npepinpe** [comment]
I spent a bit more time thinking about this, and I while I definitely like libfaketime, the licensing thing is a bit of a pain. I thought it was a nice and non-intrusive solution (which I still think it is - and it was fun to work on :smile:), but as I said in the initial issue, I guess the best bet is to add an actuator to the Zeebe to modify the actor clock. So I'm going to close this again, sorry about that :smile:

**Pull request closed without merging**
